name: Upload Settings

on:
  push:
    branches:
      - '*'

jobs:
  upload_settings:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: List Branch Folders
        id: list_branches
        run: |
          ls LiquidBounce/settings/

      - name: Upload Files
        id: upload_files
        env:
          AUTHORIZATION: ${{ secrets.AUTHORIZATION }}
        run: |
          for branch_folder in ${{ steps.list_branches.outputs.stdout }}; do
            if [ -d "LiquidBounce/settings/$branch_folder" ]; then
              for file in LiquidBounce/settings/"$branch_folder"/*; do
                curl -X POST -H "Authorization: $AUTHORIZATION" -F "settings_file=@$file" -F "name=$(basename $file)" "https://api.liquidbounce.net/api/v1/client/$branch_folder/settings/upload/global"
              done
            fi
          done
