name: Validate JSON on PR

on:
  pull_request:
    branches:
      - main

jobs:
  validate-json:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Validate JSON files
        run: |
          echo "🔍 Checking JSON files..."
          find . -type f -name "*.json" | while read file; do
            echo "Checking $file"
            jq empty "$file"
          done
          echo "✅ All JSON files are valid"
